/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anjuke_android_corendk_JNI */

#ifndef _Included_com_anjuke_android_corendk_JNI
#define _Included_com_anjuke_android_corendk_JNI
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_anjuke_android_corendk_JNI
     * Method:    stringFromJNI
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_JNITest_stringFromJNI(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
